name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build

  build-release-artifacts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build distributable
        run: |
          pyinstaller pycgtool/__main__.py --name pycgtool-${{ matrix.os }} --onefile --collect-data mdtraj --hidden-import xdrlib

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/pycgtool-${{ matrix.os }}
          token: ${{ secrets.GITHUB_TOKEN }}
