name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Build package
        run: uv build

      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish

  build-release-artifacts:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary: pycgtool-ubuntu-latest
          - os: macos-latest
            binary: pycgtool-macos-latest
          - os: windows-latest
            binary: pycgtool-windows-latest.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install prerequisites
        run: uv pip install --system pyinstaller .

      - name: Build distributable
        run: |
          pyinstaller src/pycgtool/__main__.py --name pycgtool-${{ matrix.os }} --onefile --collect-data mdtraj --collect-data pycgtool --copy-metadata pycgtool --hidden-import xdrlib

      - name: Smoke test
        shell: bash
        run: ./dist/${{ matrix.binary }} --version

      - name: Upload release artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload \
            "${{ github.event.release.tag_name }}" \
            "dist/${{ matrix.binary }}" \
            --repo "${{ github.repository }}" \
            --clobber
