# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1

    - name: Install project and dependencies
      run: |
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest --cov=pycgtool --cov-report=

    - name: Lint with flake8 - stop build if fails
      run: |
        poetry run prospector --strictness veryhigh --test-warnings --tool pyflakes

    - name: Full lint - don't stop build
      run: |
        poetry run prospector --strictness veryhigh --test-warnings --member-warnings --max-line-length 120 --zero-exit

    - name: Test that docs build
      run: |
        SPHINXBUILD="poetry run sphinx-build" make -C docs html

    - name: Check that test coverage is above 80%
      run: |
        poetry run coverage report --fail-under=80

    - name: Test that distributable package builds
      run: |
        poetry build
